version: '3.9'
services:
  mongo:
    container_name: mongodb
    image: mongo:5.0-focal
    env_file: 
      - .env
    ports:
      - 2717:27017
    volumes:
      - ./.data/db:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: 
      - .env
